// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using note_main_backend.Data;

#nullable disable

namespace note_main_backend.Migrations
{
    [DbContext(typeof(NoteDBContext))]
    partial class NoteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("note_main_backend.Models.LogEntry", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date_Added")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Is_Archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NoteID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note_Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note_Header")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
